<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Utils.fs" />
    <Compile Include="Domain\Types.fs" />
    <Compile Include="Domain\Entities\Races.fs" />
    <Compile Include="Domain\Entities\Archetypes.fs" />
    <Compile Include="Domain\Entities\Traits.fs" />
    <Compile Include="Domain\Entities\Feats.fs" />
    <Compile Include="Domain\Entities\Cantrips.fs" />
    <Compile Include="Domain\Entities\Spells.fs" />
    <Compile Include="Domain\Entities\Classes.fs" />
    <Compile Include="Domain\Entities\Subclasses.fs" />
    <Compile Include="Domain\Entities\Passives.fs" />
    <Compile Include="Domain\Character.fs" />
    <Compile Include="Domain\Entities.fs" />
    <Compile Include="Domain\Fetchers.fs" />
    <Compile Include="Model.fs" />
    <Compile Include="Update.fs" /><Compile Include="View.fs" />
    
    <Compile Include="Main.fs" />
    <Compile Include="Startup.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />

    <PackageReference Include="Bolero" Version="0.24.39" />
    <PackageReference Include="Bolero.Build" Version="0.24.39" />
    <PackageReference Include="Bolero.HotReload" Version="0.24.5" />
    <PackageReference Include="FSharp.UMX" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.*" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.*" />
  </ItemGroup>
</Project>
